"""Reference builder: convert [cite:path] into numbered references."""

from __future__ import annotations

import re
from pathlib import Path

from src.memory.problem_memory import ProblemMemory


_CITE_RE = re.compile(r"\[cite:([^\]]+)\]")


def _resolve_cite_path(problem_memory: ProblemMemory, cite_path: str) -> Path:
    raw = Path(cite_path)
    if raw.is_absolute():
        return raw

    as_posix = cite_path.replace("\\", "/")
    if as_posix.startswith("runs/"):
        return Path(as_posix)

    return (problem_memory.run_dir / raw).resolve()


def _extract_layer3_metadata(text: str) -> dict[str, str]:
    lines = text.splitlines()
    start = None
    for idx, line in enumerate(lines):
        if line.strip().lower().startswith("## layer3"):
            start = idx + 1
            break
    if start is None:
        return {}

    metadata: dict[str, str] = {}
    for line in lines[start:]:
        striped = line.strip()
        if not striped:
            continue
        if striped.startswith("## "):
            break
        if ":" not in striped:
            continue
        key, value = striped.split(":", 1)
        metadata[key.strip().lower()] = value.strip()
    return metadata


def _format_reference(index: int, meta: dict[str, str], fallback_path: str) -> str:
    title = meta.get("title") or "Unknown title"
    authors = meta.get("authors") or "Unknown authors"
    url = meta.get("url") or meta.get("reference") or fallback_path
    return f"[{index}] {authors}. {title}. {url}."


def _slugify_key(text: str, *, fallback: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9]+", "_", (text or "").strip()).strip("_")
    return value or fallback


def references_to_bibtex(references: list[str]) -> str:
    """Convert formatted references into BibTeX text."""
    entries: list[str] = []
    for idx, ref in enumerate(references, start=1):
        # Expected shape: [n] Authors. Title. URL.
        match = re.match(r"\[\d+\]\s*(.*?)\.\s*(.*?)\.\s*(.*?)\.?$", ref.strip())
        if match:
            authors = match.group(1).strip() or "Unknown authors"
            title = match.group(2).strip() or f"Untitled Reference {idx}"
            url = match.group(3).strip() or "https://example.invalid"
        else:
            authors = "Unknown authors"
            title = ref.strip() or f"Untitled Reference {idx}"
            url = "https://example.invalid"

        key = _slugify_key(title, fallback=f"ref_{idx}")
        entry = (
            f"@misc{{{key},\n"
            f"  title = {{{title}}},\n"
            f"  author = {{{authors}}},\n"
            f"  howpublished = {{\\url{{{url}}}}},\n"
            f"  note = {{Generated by reference_builder}}\n"
            f"}}"
        )
        entries.append(entry)

    return "\n\n".join(entries) + ("\n" if entries else "")


def export_references_bibtex(references: list[str], problem_memory: ProblemMemory) -> Path:
    """Convert references to BibTeX and persist as artifact/citations.bib."""
    bibtex_text = references_to_bibtex(references)
    return problem_memory.save_bibtex(bibtex_text)


def build_references(solution_text: str, problem_memory: ProblemMemory) -> tuple[str, list[str], list[str]]:
    """Convert cite paths into numbered references.

    Returns:
      converted_text, references, missing_warnings
    """
    citation_order: list[str] = []
    citation_index: dict[str, int] = {}
    missing_warnings: list[str] = []

    def _replace(match: re.Match) -> str:
        cite_path = (match.group(1) or "").strip()
        if cite_path not in citation_index:
            citation_order.append(cite_path)
            citation_index[cite_path] = len(citation_order)
        return f"[{citation_index[cite_path]}]"

    converted_text = _CITE_RE.sub(_replace, solution_text or "")

    references: list[str] = []
    for cite_path in citation_order:
        idx = citation_index[cite_path]
        target = _resolve_cite_path(problem_memory, cite_path)
        if not target.exists() or not target.is_file():
            missing_warnings.append(f"[{idx}] missing citation path: {cite_path}")
            continue

        text = target.read_text(encoding="utf-8")
        meta = _extract_layer3_metadata(text)
        references.append(_format_reference(idx, meta, fallback_path=cite_path))

    return converted_text, references, missing_warnings
