"""Reference builder: convert [cite:path] into numbered references.

将解答文本中的 [cite:path] 标记转换为带编号的引用列表，并提供 BibTeX 导出。
"""

from __future__ import annotations

import re
from pathlib import Path

from src.memory.problem_memory import ProblemMemory


# 预编译正则表达式：匹配 [cite:任意非]字符] 的引用标记
_CITE_RE = re.compile(r"\[cite:([^\]]+)\]")


def _slugify_key(text: str, *, fallback: str) -> str:
    """将文本转换为仅包含字母、数字和下划线的 BibTeX key 格式。"""
    value = re.sub(r"[^a-zA-Z0-9]+", "_", (text or "").strip()).strip("_")
    return value or fallback


def _resolve_cite_path(problem_memory: ProblemMemory, cite_path: str) -> Path:
    """把引用路径解析成可直接读取的文件路径。"""
    raw = Path(cite_path)
    if raw.is_absolute():
        return raw

    normalized = cite_path.replace("\\", "/")
    if normalized.startswith("runs/"):
        return Path(normalized)

    return (problem_memory.run_dir / raw).resolve()


def _extract_layer3_metadata(text: str) -> dict[str, str]:
    """从引用文件内容中提取 ## Layer3 区块下的键值对元数据。"""
    lines = text.splitlines()
    start_line = None
    for line_index, line in enumerate(lines):
        if line.strip().lower().startswith("## layer3"):
            start_line = line_index + 1
            break
    if start_line is None:
        return {}

    metadata: dict[str, str] = {}
    for line in lines[start_line:]:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("## "):
            break
        if ":" not in stripped:
            continue
        key, value = stripped.split(":", 1)
        metadata[key.strip().lower()] = value.strip()
    return metadata


def _format_reference(index: int, meta: dict[str, str], fallback_path: str) -> str:
    """根据编号和元数据，生成引用字符串。"""
    title = meta.get("title") or "Unknown title"
    authors = meta.get("authors") or "Unknown authors"
    url = meta.get("url") or meta.get("reference") or fallback_path
    return f"[{index}] {authors}. {title}. {url}."


def _collect_citation_order(solution_text: str) -> tuple[str, list[str]]:
    """提取引用顺序并把 cite 标记替换成编号。"""
    source_text = solution_text or ""
    citation_order: list[str] = []
    citation_index: dict[str, int] = {}
    rendered_parts: list[str] = []
    cursor = 0

    for match in _CITE_RE.finditer(source_text):
        rendered_parts.append(source_text[cursor:match.start()])
        cite_path = (match.group(1) or "").strip()
        if cite_path not in citation_index:
            citation_order.append(cite_path)
            citation_index[cite_path] = len(citation_order)
        rendered_parts.append(f"[{citation_index[cite_path]}]")
        cursor = match.end()

    rendered_parts.append(source_text[cursor:])
    return "".join(rendered_parts), citation_order


def references_to_bibtex(references: list[str]) -> str:
    """Convert formatted references into BibTeX text.

    将格式化好的引用列表（每条如 '[1] Authors. Title. URL.'）转换成 BibTeX 条目字符串。
    """
    entries: list[str] = []
    for index, reference in enumerate(references, start=1):
        # 预期格式：[数字] 作者. 标题. URL.
        match = re.match(r"\[\d+\]\s*(.*?)\.\s*(.*?)\.\s*(.*?)\.?$", reference.strip())
        if match:
            authors = match.group(1).strip() or "Unknown authors"
            title = match.group(2).strip() or f"Untitled Reference {index}"
            url = match.group(3).strip() or "https://example.invalid"
        else:
            authors = "Unknown authors"
            title = reference.strip() or f"Untitled Reference {index}"
            url = "https://example.invalid"

        key = _slugify_key(title, fallback=f"ref_{index}")
        entry = (
            f"@misc{{{key},\n"
            f"  title = {{{title}}},\n"
            f"  author = {{{authors}}},\n"
            f"  howpublished = {{\\url{{{url}}}}},\n"
            f"  note = {{Generated by build_reference}}\n"
            f"}}"
        )
        entries.append(entry)

    return "\n\n".join(entries) + ("\n" if entries else "")


def build_references(solution_text: str, problem_memory: ProblemMemory) -> tuple[str, list[str], list[str]]:
    """Convert cite paths into numbered references.

    将解答文本中的 [cite:path] 转换为编号引用。

    Args:
        solution_text: 包含 [cite:path] 标记的原始解答文本。
        problem_memory: 当前问题的记忆对象，用于解析文件路径。

    Returns:
        converted_text: 所有引用标记已被替换为数字编号后的文本。
        references: 成功生成的引用条目列表（每项形如 '[n] 作者. 标题. URL.'）。
        missing_warnings: 缺失文件或路径无效的警告信息列表。
    """
    converted_text, citation_order = _collect_citation_order(solution_text)
    citation_index = {cite_path: index for index, cite_path in enumerate(citation_order, start=1)}
    missing_warnings: list[str] = []
    references: list[str] = []

    for cite_path in citation_order:
        index = citation_index[cite_path]
        target = _resolve_cite_path(problem_memory, cite_path)
        if not target.exists() or not target.is_file():
            missing_warnings.append(f"[{index}] missing citation path: {cite_path}")
            continue

        text = target.read_text(encoding="utf-8")
        metadata = _extract_layer3_metadata(text)
        references.append(_format_reference(index, metadata, fallback_path=cite_path))

    return converted_text, references, missing_warnings
